### ISSUE TITLE
Tokens disappear when app is force-closed in latest version

### ISSUE THREAD

**Issue by droobah** [privacyidea/pi-authenticator#110] opened 2021-02-01 15:39 UTC
After upgrading to the new version, all of my tokens were removed/deleted.  I readded them and they worked until the app was force closed by swiping up.

After doing this and relaunching the app, all tokens are gone.  This is repeatable for me.  I have tried uninstalling and reinstalling the app to no avail.

1. Is there a debug version that is in TestFlight that I could use in order to send any sort of logging information to you?  
2. Is there a 'reset' function hidden in the app somewhere that will let me reset the keychain for the app in case there is an old entry causing issues?

**Comment by nilsbehlen** [comment] 2021-02-01 15:49
Hi, we have heard of this issue already. Since i'm not an apple user, is there something the user can do about keychain access?
This sounds like the access is restricted.

**Comment by droobah** [comment] 2021-02-01 15:54
Not really, the only 'fix' I've seen previously is to have a button within the app that deletes all keychain entries so they can all be re-created from scratch without permission issues.

Some keychain items survive an application re-install and I'm assuming one from an old version of this application is causing the issue having bad permissions.

**Comment by nilsbehlen** [comment] 2021-02-02 11:22
Alright, i will submit a build to testflight soon

**Comment by marcohald** [comment] 2021-02-02 13:11
we also have the same issue.
@nilsbehlen is there feed or website where i can see the actual testflight version ?
Or is this only possible via the Testflight App ?

**Comment by nilsbehlen** [comment] 2021-02-02 13:15
To my understanding you can only see it in the TestFlight App. The invite link is https://testflight.apple.com/join/hcpxWPt0 in case you didn't have it already. The build with the delete all function is currently processing in the appstore.

**Comment by marcohald** [comment] 2021-02-02 13:20
We just tested it with an new employee /phone.
the issue also happens on new devices where the PrivacyIdea App never was installed.
After a Push Token is added and the App is force closed it is deleted on the next start.

**Comment by droobah** [comment] 2021-02-02 15:05
I finally got the project to build locally and was able to reproduce the fault with a fresh install.  I'll see if I can assist finding the fault and help fix it.

**Comment by nilsbehlen** [comment] 2021-02-02 16:02
i finally also managed to reproduce this behavior using the emulator, while using a real phone this does not happen. Going to start fixing it tomorrow.

**Comment by droobah** [comment] 2021-02-02 16:05
I found the issue causing the tokens to fail for me is within the call to loadAllTokensLegacy.  If I force it to skip loading legacy tokens, it works as expected.  It even brings back all of the tokens I had previously added.

**Comment by droobah** [comment] 2021-02-02 16:40
No idea why I can't get code to display properly in my post, but hopefully what I added to my last post is halfway readable and makes sense.

**Comment by cornelinux** [comment] 2021-02-03 08:08
@nilsbehlen @droobah, this would mean that on all newly installed apps saving tokens would fail? 
Can we reproduce this by deleting all existing tokens within the app, remove the app and reinstall the app? Then the keychain/tokenlist would be empty.

**Comment by cornelinux** [comment] 2021-02-03 08:10
@marcohald @droobah There is a new build 3.0.9 in [Testflight](https://www.privacyidea.org/privacyidea-authenticator-ios-testdrive/)

**Comment by linuxchips** [comment] 2021-02-03 08:49
@cornelinux we have the same issue. we tried removing and reinstalling and the results are the same.

sometimes it happens in some android phones too, but the root cause might be different.
but on iOS, we have cases on all kinds of devices. all of the new installations and old installations have the same issue.

**Comment by cornelinux** [comment] 2021-02-03 08:57
@linuxchips That is rather unprecise. What are "old installations"? On iOS or Android.
Could you be more specific in regards to "old installations". Thanks a lot.

**Comment by nilsbehlen** [comment] 2021-02-03 09:19
Ive uploaded 3.0.10 to TestFlight which is currently in review. It implements the catch for the empty legacy token and solved the problem on my emulator.

**Comment by linuxchips** [comment] 2021-02-03 09:49
@cornelinux I was referring to iOS old installations. i.e. someone who installed the app a few weeks ago and got the update now.

but a few minutes ago, I got a case with an android 11 (a pixel phone) with an old installation having the same issue. reinstalling did not solved it for that case.

the majority of the cases are iOS, i think we have 3 androids with this issue now, versus about 15 iOS.

**Comment by nilsbehlen** [comment] 2021-02-03 13:54
There also a 3.0.10 public beta on android in review now.
@linuxchips you might want to ask people experiencing the problem to test that version to see if it fixes the problem.

**Comment by droobah** [comment] 2021-02-04 05:19
Well shucks.  The 3.0.10 testflight version still isn't keeping my tokens on my iOS device.   Would it be possible to get a build that skips loading legacy tokens entirely to confirm/deny that that is the issue?

**Comment by cornelinux** [comment] 2021-02-04 05:59
@linuxchips We have a version 3.0.10 in Play Store beta channel (please check this) and a version 3.0.10 in apple testflight. Please check these out.

**Comment by nilsbehlen** [comment] 2021-02-04 09:08
@droobah i thought the code you posted fixed the problem for you?
I will make a version that does not load legacy token.

**Comment by droobah** [comment] 2021-02-04 15:05
@nilsbehlen It DID fix it for the test build I had.  That's why I'm confused as to why it is still not functioning for me.

**Comment by nilsbehlen** [comment] 2021-02-04 15:50
@droobah ok that is really confusing. Can you check out 3.0.11 on testflight when it becomes available, it has legacyload completely disabled and does not touch the code that caused your problem. It would be really good if we were able to pinpoint these problems to the legacyload feature (or not).

**Comment by marcohald** [comment] 2021-02-04 16:21
The version 3.0.10 fixed the Issue with the disappearing Push Token for our User

**Comment by nilsbehlen** [comment] 2021-02-04 16:23
Thats good to hear, did it also restore token that previously disappeared?

**Comment by marcohald** [comment] 2021-02-04 16:26
I can't answer the Question because the tokens before were already cleaned up on the server.

**Comment by nilsbehlen** [comment] 2021-02-04 16:28
alright, thanks for the feedback!

**Comment by sluitz** [comment] 2021-02-04 16:44
On my phone version 3.0.10 did not fix the issue with disappearing tokens after restarting the app. These tokens were registered after using the delete all tokens button.

**Comment by cornelinux** [comment] 2021-02-04 16:47
@droobah @sluitz What kind of policies did you have in place?
Especially enrollment policies like ``tokenissuer`` and ``tokenlabel``. Which toke parameters did you use?
...trying to identify the differences here, thanks a lot!

**Comment by sluitz** [comment] 2021-02-04 18:27
The PI server is version 3.5.
I removed all special characters from tokenissuer and tokenlabel. 

`action: **{'tokenissuer': 'LZOnline', 'tokenlabel': '<u><r>'}**`
Registration URL (in SMS gateway settings is)`https://luxzeplin.org/mfa/ttype/push`

**Comment by droobah** [comment] 2021-02-05 03:35
@nilsbehlen The build 3.0.11 now has working tokens for me.  So definitely something in the legacy token loading code is broken for me somehow.

**Comment by droobah** [comment] 2021-02-05 03:43
@cornelinux I'm using <u>_<s> for my tokenlabel, and the token issuer is just Company Name

**Comment by sluitz** [comment] 2021-02-05 03:52
Same here. 3.0.11 is working for me: Push notifications work, enrolling new tokens and deleting tokens both work and tokens are still there after a restart of the app.

**Comment by droobah** [comment] 2021-02-05 04:37
I wonder if the legacy token function is throwing a different exception on our devices, and not the FormatException causing the function to terminate prematurely.

**Comment by nilsbehlen** [comment] 2021-02-05 11:58
thanks for the feedback.
We will make the legacyloading manual through the settings (#115), that way we are able to show the error and it does not crash the whole loading process when the app starts.

**Comment by cornelinux** [comment] 2021-03-20 06:22
@nilsbehlen @timosturm I think the root cause is officially fixed.
If we get other issues via the wrapper, we should open new issues (if at all) for that.

**Closed** 2021-03-25 09:46 UTC
Labels: Prio: High, bug
