### ISSUE TITLE
support SHA256 and SHA512

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/pi-authenticator#37] opened 2020-01-21 10:25 UTC
App Version: 0.0.1

The current native app supports the Hash algorithms SHA256 and SHA512 for TOTP and HOTP.
THis app should also do this.

**Comment by timosturm** [comment] 2020-01-23 09:57
Please provide more information.
+ What are you doing
+ Expected behavior
+ Actual behavior 
+ How to reproduce the problem

**Comment by cornelinux** [comment] 2020-01-23 10:08
> Please provide more information.
> 
>     * What are you doing

I am enrolling an HOTP or TOTP token in privacyIDEA with SHA256 or SHA512 hash.

> 
>     * Expected behavior

Be able to scan the QR code.

> 
>     * Actual behavior

App says: That sha256 or 512 is not supported.

> 
>     * How to reproduce the problem

Create an HOTP token with SHA256 in privacyidea.
Scan this:

![grafik](https://user-images.githubusercontent.com/1908620/72975149-9a556100-3dd0-11ea-9f6c-d5f8f82fd785.png)

OTPs:
205245
436775
857325

**Comment by timosturm** [comment] 2020-01-23 11:41
This should be fixed now. The problem was parsing the otpauth url.

**Closed by timosturm** 2020-01-23 11:41 UTC
Labels: Prio: High
